### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by badpenguin** [kickofitall/group-favorite-folders#1]
How this is supposed to work?
It does absolutely nothing after I've installed it.

**Comment by kickofitall** [comment]
As the description says: **The plugin only affects the favorites folders with the compact view (flat, no hierarchy).**

First, the [favorites folders must be displayed](http://mzl.la/1ApHmDc).

If you haven't added any folders to your favorites, nothing may appear here.
You can add folders to favorites by right-clicking on a folder and checking "favorite folder" in the context menu.

The plugin then sorts the folders in the favorites view.

Does that help?

**Comment by badpenguin** [comment]
Yup sorry! I've favourite folder but still using hierarchy, non flat :-(
